import { Flex, Heading, Text } from "@radix-ui/themes"
import type { NextPage } from "next"
import Head from "next/head"
import Link from "next/link"
import Image from "next/image"

const Offline: NextPage = () => {
    return (
        <>
            <Head>
                <title>Offline</title>
                <meta name="description" content="Generated by create next app" />
                <Link rel="icon" href={'favicon.ico'}></Link>
            </Head>
            <Flex>
                <Image src={'/offline.png'} alt="Offline" fill sizes='(width: 768px) 100%' />
                <Heading>Offline</Heading>
                <Text>Unable to connect to the server</Text>
            </Flex>
        </>
    )
}

export default Offline